- name: Deploy Hospital Management System using Docker
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Check Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Show Docker version
      debug:
        var: docker_version.stdout

    - name: Build Docker image
      command: docker build -t hospital-app .

    - name: Stop old container if running
      command: docker rm -f hospital-container
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 8080:80 --name hospital-container hospital-app