- name: Deploy Hospital App using Docker
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Check Docker version
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Show Docker version
      debug:
        var: docker_version.stdout

    - name: Build Docker Image (correct path)
      command: docker build -t hospital-app ..
      args:
        chdir: "{{ playbook_dir }}"

    - name: Stop old container
      command: docker rm -f hospital-container
      ignore_errors: yes

    - name: Run container
      command: docker run -d -p 8080:80 --name hospital-container hospital-app