- name: Deploy Hospital App
  hosts: servers
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Build Image
      command: docker build -t hospital-app ..

    - name: Run Container
      command: docker run -d -p 8080:80 hospital-app