name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Project Files
        run: ls -R

      - name: CI Passed
        run: echo "Project is valid and CI passed"